version: '3.9'

services:
  frontend:
    container_name: frontend
    image: ciganov-net/frontend:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '4200:4200'
    networks:
      - ciganov-net

networks:
  ciganov-net:
    external: true
