name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          timeout: 30m
          command_timeout: 30m
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            REPO=${{ github.event.repository.name }}
            cd ~/ciganov/$REPO
            git pull
            docker compose -f compose.yml up -d --build